version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-dnd
    environment:
      POSTGRES_DB: dnd_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dnd
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  app:
    build: .
    container_name: spring-dnd-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dnd_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      - character_photos:/app/uploads/character-photos

volumes:
  postgres_data:
  character_photos:
