package com.matheusorestes.dndCharacterSheet.domain.rules;

/** Weapon groups and individual weapons used by standard D&D 5e class proficiencies. */
public enum WeaponProficiency {
    SIMPLE_WEAPONS,
    MARTIAL_WEAPONS,
    BATTLEAXE,
    BLOWGUN,
    CLUB,
    CROSSBOW_HAND,
    CROSSBOW_HEAVY,
    CROSSBOW_LIGHT,
    DAGGER,
    DART,
    FLAIL,
    GLAIVE,
    GREATAXE,
    GREATSWORD,
    HALBERD,
    HANDAXE,
    JAVELIN,
    LANCE,
    LIGHT_HAMMER,
    LONGBOW,
    LONGSWORD,
    MACE,
    MAUL,
    MORNINGSTAR,
    NET,
    PIKE,
    QUARTERSTAFF,
    RAPIER,
    SCIMITAR,
    SHORTBOW,
    SHORTSWORD,
    SICKLE,
    SLING,
    SPEAR,
    TRIDENT,
    WAR_PICK,
    WARHAMMER,
    WHIP
}
